name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10 # Optional: specify a pnpm version

    - run: |
        pnpm install --ignore-scripts --frozen-lockfile
        tar -xzC public -f tradingview/tradingview.tgz # manually inline postinstall script

    - run: pnpm exec vitest run