name: Lint
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10 # Optional: specify a pnpm version

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Check if tradingview directory exists
        id: check_tradingview
        run: |
          if [ -d "tradingview" ] && [ -f "tradingview/tradingview.tgz" ]; then
            echo "tradingview_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tradingview_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          if [ "${{ steps.check_tradingview.outputs.tradingview_exists }}" = "true" ]; then
            mkdir -p public
            tar -xzC public -f tradingview/tradingview.tgz
          fi

      - name: Lint PR Title
        run: |
          echo "${PR_TITLE}" | pnpx commitlint --config commitlint.config.ts
        env:
          PR_TITLE: '${{ github.event.pull_request.title }}'

      - name: ESLint
        run: |
          pnpm lint
