name: Lint
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install commitlint dependencies
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Lint PR Title
        run: |
          echo "${PR_TITLE}" | commitlint --config commitlint.config.ts
        env:
          PR_TITLE: '${{ github.event.pull_request.title }}'

      # Skip ESLint for now as it requires full dependency installation
      # - name: ESLint
      #   run: |
      #     pnpm lint
