name: Lint
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up pnpm
          uses: pnpm/action-setup@v3
          with:
            version: 10 # Optional: specify a pnpm version

      - name: Install dependencies
        run: |
          pnpm install @commitlint/config-conventional

      - name: Lint PR Title
        run: |
          echo "${PR_TITLE}" | pnpx commitlint --config commitlint.config.ts
        env:
          PR_TITLE: '${{ github.event.pull_request.title }}'

      - name: ESLint
        run: |
          pnpm lint
